//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrustWrapper.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynchroRequest", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class SynchroRequest : object
    {
        
        private string SerialNumField;
        
        private string[] responsesField;
        
        private string userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNum
        {
            get
            {
                return this.SerialNumField;
            }
            set
            {
                this.SerialNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] responses
        {
            get
            {
                return this.responsesField;
            }
            set
            {
                this.responsesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModel", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class ResponseModel : object
    {
        
        private string ResponseCodeField;
        
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                this.ResponseMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestModel", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class RequestModel : object
    {
        
        private string userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCheckResponseModel", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class UserCheckResponseModel : object
    {
        
        private string ResponseCodeField;
        
        private string ResponseMessageField;
        
        private EntrustWrapper.Model.UserBasicInfo UserInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                this.ResponseMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntrustWrapper.Model.UserBasicInfo UserInfo
        {
            get
            {
                return this.UserInfoField;
            }
            set
            {
                this.UserInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBasicInfo", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class UserBasicInfo : object
    {
        
        private string FullnameField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname
        {
            get
            {
                return this.FullnameField;
            }
            set
            {
                this.FullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnlockClearQAResponseModel", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class UnlockClearQAResponseModel : object
    {
        
        private EntrustWrapper.Model.QResponse QResponseField;
        
        private string ResponseCodeField;
        
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntrustWrapper.Model.QResponse QResponse
        {
            get
            {
                return this.QResponseField;
            }
            set
            {
                this.QResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                this.ResponseMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QResponse", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class QResponse : object
    {
        
        private string[] QsField;
        
        private string ResponseCodeField;
        
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Qs
        {
            get
            {
                return this.QsField;
            }
            set
            {
                this.QsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                this.ResponseMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthRequest", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class AuthRequest : object
    {
        
        private string CustIDField;
        
        private string PassCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustID
        {
            get
            {
                return this.CustIDField;
            }
            set
            {
                this.CustIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassCode
        {
            get
            {
                return this.PassCodeField;
            }
            set
            {
                this.PassCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthResponse", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class AuthResponse : object
    {
        
        private bool AuthenticatedField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Authenticated
        {
            get
            {
                return this.AuthenticatedField;
            }
            set
            {
                this.AuthenticatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateUserRequest", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class UpdateUserRequest : object
    {
        
        private string EmailField;
        
        private string FullNameField;
        
        private string PhoneField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerialNoRequest", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class SerialNoRequest : object
    {
        
        private string CustIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustID
        {
            get
            {
                return this.CustIDField;
            }
            set
            {
                this.CustIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerialNoResponse", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    public partial class SerialNoResponse : object
    {
        
        private string MessageField;
        
        private string SerialnoField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serialno
        {
            get
            {
                return this.SerialnoField;
            }
            set
            {
                this.SerialnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAuthWrapper")]
public interface IAuthWrapper
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/SynchronizeToken", ReplyAction="http://tempuri.org/IAuthWrapper/SynchronizeTokenResponse")]
    System.Threading.Tasks.Task<EntrustWrapper.Model.ResponseModel> SynchronizeTokenAsync(EntrustWrapper.Model.SynchroRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/UnlockUser", ReplyAction="http://tempuri.org/IAuthWrapper/UnlockUserResponse")]
    System.Threading.Tasks.Task<EntrustWrapper.Model.ResponseModel> UnlockUserAsync(EntrustWrapper.Model.RequestModel request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/CheckUser", ReplyAction="http://tempuri.org/IAuthWrapper/CheckUserResponse")]
    System.Threading.Tasks.Task<EntrustWrapper.Model.UserCheckResponseModel> CheckUserAsync(EntrustWrapper.Model.RequestModel request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/UnlockUserandClearQA", ReplyAction="http://tempuri.org/IAuthWrapper/UnlockUserandClearQAResponse")]
    System.Threading.Tasks.Task<EntrustWrapper.Model.UnlockClearQAResponseModel> UnlockUserandClearQAAsync(EntrustWrapper.Model.RequestModel request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/AuthMethod", ReplyAction="http://tempuri.org/IAuthWrapper/AuthMethodResponse")]
    System.Threading.Tasks.Task<EntrustWrapper.Model.AuthResponse> AuthMethodAsync(EntrustWrapper.Model.AuthRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/UpdateUserDetails", ReplyAction="http://tempuri.org/IAuthWrapper/UpdateUserDetailsResponse")]
    System.Threading.Tasks.Task<EntrustWrapper.Model.ResponseModel> UpdateUserDetailsAsync(EntrustWrapper.Model.UpdateUserRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/GetTokenSerial", ReplyAction="http://tempuri.org/IAuthWrapper/GetTokenSerialResponse")]
    System.Threading.Tasks.Task<EntrustWrapper.Model.SerialNoResponse> GetTokenSerialAsync(EntrustWrapper.Model.SerialNoRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
public interface IAuthWrapperChannel : IAuthWrapper, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
public partial class AuthWrapperClient : System.ServiceModel.ClientBase<IAuthWrapper>, IAuthWrapper
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public AuthWrapperClient() : 
            base(AuthWrapperClient.GetDefaultBinding(), AuthWrapperClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAuthWrapper.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public AuthWrapperClient(EndpointConfiguration endpointConfiguration) : 
            base(AuthWrapperClient.GetBindingForEndpoint(endpointConfiguration), AuthWrapperClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public AuthWrapperClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(AuthWrapperClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public AuthWrapperClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(AuthWrapperClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public AuthWrapperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<EntrustWrapper.Model.ResponseModel> SynchronizeTokenAsync(EntrustWrapper.Model.SynchroRequest request)
    {
        return base.Channel.SynchronizeTokenAsync(request);
    }
    
    public System.Threading.Tasks.Task<EntrustWrapper.Model.ResponseModel> UnlockUserAsync(EntrustWrapper.Model.RequestModel request)
    {
        return base.Channel.UnlockUserAsync(request);
    }
    
    public System.Threading.Tasks.Task<EntrustWrapper.Model.UserCheckResponseModel> CheckUserAsync(EntrustWrapper.Model.RequestModel request)
    {
        return base.Channel.CheckUserAsync(request);
    }
    
    public System.Threading.Tasks.Task<EntrustWrapper.Model.UnlockClearQAResponseModel> UnlockUserandClearQAAsync(EntrustWrapper.Model.RequestModel request)
    {
        return base.Channel.UnlockUserandClearQAAsync(request);
    }
    
    public System.Threading.Tasks.Task<EntrustWrapper.Model.AuthResponse> AuthMethodAsync(EntrustWrapper.Model.AuthRequest request)
    {
        return base.Channel.AuthMethodAsync(request);
    }
    
    public System.Threading.Tasks.Task<EntrustWrapper.Model.ResponseModel> UpdateUserDetailsAsync(EntrustWrapper.Model.UpdateUserRequest request)
    {
        return base.Channel.UpdateUserDetailsAsync(request);
    }
    
    public System.Threading.Tasks.Task<EntrustWrapper.Model.SerialNoResponse> GetTokenSerialAsync(EntrustWrapper.Model.SerialNoRequest request)
    {
        return base.Channel.GetTokenSerialAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthWrapper))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthWrapper))
        {
            return new System.ServiceModel.EndpointAddress("http://172.16.248.237/EntrustWrapper/AuthWrapper.svc");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return AuthWrapperClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAuthWrapper);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return AuthWrapperClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAuthWrapper);
    }
    
    public enum EndpointConfiguration
    {
        
        BasicHttpBinding_IAuthWrapper,
    }
}
